// <auto-generated />
namespace Dev_Appdb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AlterTableUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208021330105_AlterTableUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1b227jNhB9L9B/EPTUFlgrl11gu7B3kY2TImhzQZzsa0BLY4coRaok5U2+rQ/9pP5CScm6UrIuVhKnyEMAi5czM+TMcDjD/Pv3P+MvDz6xVsAFZnRi74/2bAuoyzxMlxM7lIt3H+0vn3/8YXzi+Q/Wt2TcoR6nZlIxse+lDD45jnDvwUdi5GOXM8EWcuQy30Eecw729n519vcdUBC2wrKs8XVIJfYh+lCfx4y6EMgQkXPmARHrdtUzi1CtC+SDCJALE3sKq7ujIPDmo3isbR0RjBQfMyAL2wref7oVMJOc0eUsQBIjcvMYgOpfICJgzfWn4H1bxvcONOMOopRJBcdoL8HtVCQl1IkSXj5qtiLBJvY50DA/Qo35HR4LDarpirMAuHy8hkVu3plnW05xrlOenE4tzdMsTOwzKg8PbOsiJATNCaQrpZZyJhmH34ACRxK8KyQlcLX9Zx5EIhiUS3SmIFyOXcQSUmpflGLZ1il+AO8PoEt5n5I7Rw9JywelXbcUKzVUcyQPoYK7zZSPOSiOlSbwZjk3I+m1ukJ4A0zM4GaU28AbiJ9Ysqn6S3D07xtlTZ2hYqYGgTpyJV6lMF8ZI4BoM8oFWuFlZFXVq25b10CifnGPg9jGR7rvLh1wypl/zch6TtJ+N2MhdzVDrKLzBvElyCI3Yyczy43Gqjexj7Emm9/VWNspzfbGeitCxHFXUz3c2lQvmA8die7vbU31CgnxnXHv+Smrw26Bud+TAfVzWwZOfITJoHK38YDDeeQ3X2qitPZe3zB87+O99Lw+3iuZ9z8ONRhV0SYhwPX3s5PX2sJoD9IHH3YnyHoz6bahaOf12RhiVcZX2mTv4t4suEobjcgq6+kSVh0JwVwckc7xk4Z1RRlOqGdtivFitU9iQ6XlIZE4INhVhCf2L8aa1OAl/Dfg7Y1G+wak8pTAtatCRDkEITnCVJpuFVMXB4hsoF6a0+Hepxc7pVDumUIAVPvS"
                       + "DQvZlvT6OmRST4mUDommxRk7OXXYrCWZctZtaYWmZvsZHX8d9MNU7gbl2C+v4viSToGABCv21MpFIeEiz7RUZSneAEplsPxMGmWs+3Z0B9el2A/p01rNAJ7GDaujIJh+NdRJD56BLDjLzJUVNMDQnuLc6MJozo2bG+bG+mrMjZtLc3NyFxnPLsu5IVWX6fImNPjdlNlkfYxdbHC0DQCFrVSjWoibO7tMWWt8R4P3yDFZtewN7qK/iMnJmWpslhV14rRokj51avKn43MUBCoUzOVT1y3WLE6mHr+bdU9n+jGG44qKrGbKbUpJxfVoCaVeHTZ7cIq5kCqoQnOkI5djzzeGNdlnQqYukVq4AyWD9e/U/AvZ5FEVQrZup0oUX7u86LZS3ltjWpTARgTxmkDumJHQp5s9YT1K7sqTB8o1t8cqhvJ5uGJPe8RcoFAWsyZ+qMcqXg/ycMWervLGsb0pbdzelT8TLd/eHi25LOSRkjYTZeyUdNM4SQ39N8KOoi21sjQzC9rV0qoQWlha9bTananSmc7akqZGizDrxvY4caozDxK3tEfIsoZ5lKy1gwWU05AFMyh3tsddZxfzaOuml/RGbx5k5zyImYns6kGqEFp4kOppdWuZJDDza1mdDN2EMuhZXUo4lgy30NdNZ5I8YllvkvY3C27i72UseJg480n9gHGbKQ9Jqae3mtLtZby+STQ/ETGuFvEQ21LLs8KevlbMHoUEf6QHjGZ/kWOClbzZgHNE8QKEvGF/gro9qpvPx9I7kx5vQBwhPLLLD0GwXoLGOkzHpLVRmKErxN17xI06yADVh0iCbR94lED6Pu/ow4tZvdC4cpjqRW+oYvVijpvkeiVPKZ5E3UuvKCqV/bC7sucfSVRiRgX6Ld9ADAZc88Qhwf/JRw8/b/dsoQ2rfV8l9DHcNwfwCl8jvLLzrvKdwVDo5jOCSmT9aOCFzuk3E+vyOqB5ZZ6gMt+vdF7EiMPrziX93vX35yy4R7K1"
                       + "pbfbVfZW2z1oMbxYZetR1d95FanJZ+1g1dws3tWk/NqUz+PbufKdc31mxv5q+8J6FaruEdvV3KtgX6Qa3738HnvWHay5dxcnv0W1lflhautm1klZU+7fl5QVC7zMIPQ/M1FwC3aUjjmjC5aYc4mjZIhxqkukggp0xCVeIFeqbheEiB54fkMkjC5Gc/DO6GUog1AqkcGfk8J7We0WNtGPHhAUeR5fBtGrwCFEUGxiHRdd0q8hJl7K92lFTFIDof3NOkbXeyl1rL58TJEuGG0JtF6+1E3egB8QBSYu6Qzp+KuOt+Y1LK7YeIrRkiNfrDGy+epTqZ/nP3z+Dyszk7qANwAA"; }
        }
    }
}
