// <auto-generated />
namespace Dev_Appdb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class CreateDatabase : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207251247504_CreateDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1b227jNhB9L9B/EPRYYK1cdoFtYO8iGydF0OaCOMlrQEtjhyhFqiTlxt+2D/2k/kJJyZIlUXdrN94iDwuseTlz4cxwOKP8+/Wf8ecXn1gr4AIzOrEPRwe2BdRlHqbLiR3KxbuP9udPP/80Pvf8F+sxWXes16mdVEzsZymDE8cR7jP4SIx87HIm2EKOXOY7yGPO0cHBr87hoQMKwlZYljW+C6nEPkQ/1M8zRl0IZIjIFfOAiM24mplFqNY18kEEyIWJPYXV02kQePNRvNa2TglGio8ZkIVtBe9PHgTMJGd0OQuQxIjcrwNQ8wtEBGy4Pgnet2X84Egz7iBKmVRwjPYS3E5FUkKdK+HlWrMVCTaxr4CG2RVqze+wzg2ooVvOAuByfQeLzL5Lz7ac/F6nuDndWtinWZjYl1QeH9nWdUgImhNINaVUOZOMw29AgSMJ3i2SErg6/ksPIhEMygU6UxAuxy5iCSl1LsqwbOsCv4D3B9ClfE7JXaGXZOSDsq4HipUZqj2Sh1DCXT3lMw6KY2UJvFnOeiStq1uEa2BiButRHgJvIH5iyabqX4Kj/3+vvKkzVMzUIFCnrsSrFOYLYwQQbUa5Riu8jLyqXOu2dQckmhfPOIh9fKTnntIFF5z5d4xs9iTjTzMWclczxEom7xFfgsxzM3a2blnrrPoQ+zhrcvhdnbWd0ezurA8iRBx3ddXjnV31mvnQkejhwc5Uz32EyaBk24SB4cLSW0AxUVq78COGv/u4sN7Xx4WTff/j+5ZRlXIRAlz//u7ktbUw2oP00Yf9yTTeXLptPtZZP7V5RmmSoV32KZ7dZhjpoJFebGe65BanQjAXR6Qz/KS5TV6Gc+pZdYlObPZJgqSsPCQSBwS7ivDE/sXQSQVewn8D3sFodGhAqkgJXIcqRFRAEJIjTKUZVjF1cYBIDfXCng6PH63slEJxZgoBUB1LaxTZlvTmTWBST4kULokm5YydjDnUW8nW"
                       + "OKuOtMRSt+cZXX8d7MM07gbjOCxqcXxDp0BAghVHahWikHCRZ3qq8hRvAKMyWP5OFmXofTe6g9tSHIf0ba12AE/zhtVpEEy/GOakF89A5oLlNpTlLMCwnvze6NVk7o2HG/bG9mrsjYcLezNy5xnfvhgzS8pelMVDaIi7KbOJfoxTbAi0DQC5o1SrWoibubtMWStiR0P0yDBZpvaGcNFfxOTmTC12Wxp04tpgUkN0KoqI4ysUBCoVzBQVNyPWLK4onr2bda/p+TGG44qS0l7KbUpJ5fVoCYVZnTZ7cIG5kCqpQnOkM5czzzeWNflnQqaqmph7AyWL9f9T98+VVEdlCFu9XShRfB3yotdK8WyNbVEVFxHEKxK5M0ZCn9ZHwmqUzJMnC5QZbo+VT+WzcPmZ9oiZRKEoZkX+UI2Vfx5k4fIzXeWNc3tT2ni8K38mWna8PVryWMgiJWMmytgp2KZxkxr2b6QdeV9q5WlmKbCrp5UhtPC08m2VJ1NmM52tJa0P5mE2g+1x4npfFiQeaY+wqd1lITZDr+nrb/65d/5p1vm6+mcZQgv/LN9WpcukPJjVZXmpsQ5l0JuwUM7LWV9hrpvNJFW6ot0k428e3MTf63jwMFncN40DxluhuCSlnr4ZCm+D8SZPb/4KwUjc4yW2pdSzwp5O2mdrIcEf6QWj2V/kjGAl73bBFaJ4AULesz9Bvc3Uu+Jj4VOGHp8ZOEJ4ZJ+/NcBaBY1djo4lYaPtQVeIu8+IG12GAWr7kQS7fkNQAOn7BUEfXszegMaVw/QGekPlewNz3CTXD9Kt/ybmXmjUlxr7cXdjz/bhSzGj9vcubfY2qH276H1c4c2lfsDu+Q92g5T2xYdCN9vepci6yf1KN9+bi3XpZjdr5ht0kvu1evMYccLauQXdu1/8PRvEkWxt6e13V7jVcQ/avM13hXp0offeRCoqRHvY5TWbTRVFtDbt3vi9q2LnXN+ZcbzavRFchqpnxG494jLYV+ke"
                       + "d28Xx5F1D3vE3cXJHlFlJ3mYXrBZx1HelPmbE+XFAi+3EPovUCi4OT9K11zSBUvcucBRssS41SVSSQU65RIvkCvVtAtCRB8kPiISRg+jOXiX9CaUQSiVyODPSe77Th0W6uhHDe88z+ObIPqKbQgRFJtY50U39EuIiZfyfVGSk1RA6HizydH1WUqdqy/XKdI1oy2BNupLw+Q9+AFRYOKGzpDOv6p4a9ZhXmPjKUZLjnyxwdjuVz+V+Xn+y6f/AGRGXEs1NQAA"; }
        }
    }
}
